# Generated by Django 4.1.3 on 2022-11-07 19:13

from django.db import migrations, models
import manticore.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=2500, unique=True)),
                ('date', models.DateTimeField(default='CURRENT_TIMESTAMP')),
                ('image', models.TextField(blank=True, null=True)),
                ('thumb', models.TextField(blank=True, null=True)),
                ('cse', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='XxxHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', manticore.models.fields.RTField(default='')),
                ('image', models.CharField(default='', max_length=5000)),
                ('thumb', models.CharField(default='', max_length=5000)),
                ('cse', models.JSONField(blank=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
